measurement/urls.py
from django.urls import path
from . import views

app_name = 'measurement'
urlpatterns = [
    
    path('', views.index, name='index'),
    path('customer/<int:pk>', views.customerDetail, name='customer-detail'),
    path('customer/create/', views.customerCreate, name='customer-create'),
    path('customer/update/<int:pk>/', views.customerUpdate, name='customer-update'),
    path('customer/delete/<int:pk>/', views.customerDelete, name='customer-delete'),
    path('clothe/create/', views.ClotheCreateView.as_view(), name='clothe-create'),
    path('clothe/update/<int:pk>/', views.ClotheUpdate.as_view(), name='clothe-update'),
    path('clothe/<int:pk>/delete/', views.ClotheDeleteView.as_view(), name='clothe-delete'),
    path('about', views.about, name='about'),

]

tailor/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('measurement.urls')),
    
]

users/urls.py
from django.urls import path
from users.views import RegistrationView, login_view, logout_view

app_name = 'users'
urlpatterns = [
   
    path('register/', RegistrationView.as_view(), name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    
]

measurement/models.py
from collections.abc import Iterable
from django.db import models

# Create your models here.
class Customer(models.Model):
    first_name = models.CharField(max_length=30) 
    last_name = models.CharField(max_length=30)
    adress = models.TextField()
    phone_number = models.IntegerField()
    email = models.EmailField(max_length=254)
    joined_date = models.DateField()


    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'
    
class Clothe(models.Model):
    customer = models.ForeignKey(Customer, on_delete = models.CASCADE)
    style = models.CharField(max_length=150)
    price_charge = models.DecimalField(max_digits=10, decimal_places=2)
    deposit = models.DecimalField(max_digits=10, decimal_places=2)
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    length = models.IntegerField()
    waist = models.IntegerField()

    def save(self, *args, **kwargs) -> None:
        self.balance = self.price_charge - self.deposit
        return super().save(*args, **kwargs)
    
    def __str__(self) -> str:
        return self.style
    

measurement/forms.py
from django.forms import ModelForm
from django import forms
from .models import Customer, Clothe



class CustomerForm(ModelForm):
    
    class Meta:
        model =  Customer
        fields = ['first_name', 'last_name', 'adress', 'phone_number', 'email', 'joined_date']
        widgets = {
            'joined_date': forms.DateInput(attrs={'type': 'date'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["first_name"].widget.attrs.update({"class": "form-control"})
        self.fields["last_name"].widget.attrs.update({"class": "form-control"})
        self.fields["adress"].widget.attrs.update({"class": "form-control"})
        self.fields["phone_number"].widget.attrs.update({"class": "form-control"})
        self.fields["email"].widget.attrs.update({"class": "form-control"})
        self.fields["joined_date"].widget.attrs.update({"class": "form-control"})


class ClotheForm(ModelForm):
    class Meta:
        model = Clothe
        fields = ['customer', 'style', 'price_charge', 'deposit', 'length', 'waist']
    
        widgets = {
            'customer': forms.Select(attrs={"class": "form-control"}),
            'style': forms.TextInput(attrs={"class": "form-control"}),
            'price_charge': forms.NumberInput(attrs={"class": "form-control"}),
            'deposit': forms.NumberInput(attrs={"class": "form-control"}),
            'balance': forms.NumberInput(attrs={"class": "form-control"}),
            'length': forms.NumberInput(attrs={"class": "form-control"}),
            'waist': forms.NumberInput(attrs={"class": "form-control"}),
        } 

    '''
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["customer"].widget.attrs.update({"class": "form-control"})
        self.fields["sytle"].widget.attrs.update({"class": "form-control"})
        self.fields["price_charge"].widget.attrs.update({"class": "form-control"})
        self.fields["deposit"].widget.attrs.update({"class": "form-control"}) 
        self.fields["length"].widget.attrs.update({"class": "form-control"})
        self.fields["waist"].widget.attrs.update({"class": "form-control"}) 


'''

measurement/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from .models import Customer, Clothe
from .forms import CustomerForm, ClotheForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView


# Create your views here.
def index(request):
    customers = Customer.objects.all()
    context = {'customers': customers}
    return render(request, 'measurement/home.html', context)

def customerDetail(request, pk):
    customer = Customer.objects.get(pk=pk)
    clothes = Clothe.objects.all().filter(customer=customer.id)
    context = {'customer':customer, 'clothes': clothes}
    return render(request, 'measurement/detail.html', context)


def customerCreate(request):
    if request.method == 'POST':
        form = CustomerForm(request.POST)
        if form.is_valid():
               
            form.save()
        
            return HttpResponseRedirect(reverse('measurement:index',))
    else:

        form = CustomerForm()
    return render(request, 'measurement/customer_form.html', {'form':form})

def customerUpdate(request, pk):
    
    customer = get_object_or_404(Customer, pk=pk)
   
    if request.method == 'POST':
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():

            form.save()
            return HttpResponseRedirect(reverse('measurement:index'))
    else:
        form = CustomerForm(instance=customer)
        return render(request, 'measurement/customer_form.html', {'form':form})
    

def customerDelete(request, pk):
    customer = Customer.objects.get(pk=pk)
    customer.delete()
    return HttpResponseRedirect(reverse('measurement:index'))


class ClotheCreateView(CreateView):
    model = Clothe
    form_class = ClotheForm
    template_name = 'measurement/customer_form.html'
    success_url = reverse_lazy('measurement:index')


class ClotheUpdate(UpdateView):
    model = Clothe
    form_class = ClotheForm
    
    template_name = 'measurement/customer_form.html'
    success_url = reverse_lazy('measurement:index')


class ClotheDeleteView(DeleteView):
    model = Clothe
    
    success_url = reverse_lazy('measurement:index')
    

def about(request):
    return render(request, 'measurement/about.html')

    

measurement/templates/measurement/about.html
{% extends "measurement/base.html" %} {% block content %}
<div class="container">
    <h2>Where does it come from?</h2>
  <p>
    Contrary to popular belief, Lorem Ipsum is not simply random text. It has
    roots in a piece of classical Latin literature from 45 BC, making it over
    2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney
    College in Virginia, looked up one of the more obscure Latin words,
    consectetur, from a Lorem Ipsum passage, and going through the cites of the
    word in classical literature, discovered the undoubtable source. Lorem Ipsum
    comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum"
    (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a
    treatise on the theory of ethics, very popular during the Renaissance.
</p>
     <p>
    The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line
    in section 1.10.32. The standard chunk of Lorem Ipsum used since the 1500s
    is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from
    "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact
    original form, accompanied by English versions from the 1914 translation by
    H. Rackham.
  </p>
</div>

{% endblock content %}

measurement/templates/measurement/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'measurement/bootstrap.min.css' %}">
    
    <title>Document</title>
</head>
<body>
    
    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'measurement:index' %}">Tailor</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav me-auto">
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'measurement:index' %}">Home
                  <span class="visually-hidden">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'measurement:customer-create' %}">Add Customer</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'measurement:clothe-create' %}">Add Clothe</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">About</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <a class="dropdown-item" href="#">Something else here</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Separated link</a>
                </div>
              </li>
              
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">Register</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
              </li>
              {% else %}
              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Login</a>
              </li>
              {% endif %}
              
              
            </ul>
            <form class="d-flex">
              <input class="form-control me-sm-2" type="search" placeholder="Search">
              <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
      <div class="container">
        {% block content %}{% endblock content %}
      </div>

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

measurement/templates/measurement/clothe_confirm_delete.html
    {% extends "measurement/base.html" %}

{% block content %}
    <form method="POST", action="">
        {% csrf_token %}
       
    <p>Are you sure you want to delete "{{ object }}"?</p>
        <button class="btn btn-lg btn-primary" type="submit">Confirm</button>
    </form>
{% endblock content %}

measurement/templates/measurement/customer_form.html
{% extends "measurement/base.html" %}

{% block content %}
    <form method="POST", action="">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group mb-3">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
          <p class="help" id="{{ field.auto_id }}_helptext">
            {{ field.help_text|safe }}
          </p>
        {% endif %}
    </div>
    {% endfor %}
        <button class="btn btn-lg btn-primary" type="submit">Submit</button>
    </form>
{% endblock content %}

measurement/templates/measurement/detail.html
{% extends "measurement/base.html" %}

{% block content %}
    <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
        <h3 class="card-header">{{customer.first_name }} {{customer.last_name }}</h3>
        <div class="card-body">
        <h5 class="card-title">{{ customer.phone_number }}</h5>
        <p class="card-text">{{ customer.adress }}</p>
        </div>
    </div>
    
{% comment "" %}
clothe list view  for each associated customer
{% endcomment %}

    <div class='ml-3'>
        <h4 class='ml-5'>Clothe</h4>
       <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Style</th>
            <th scope="col">Price</th>
            <th scope="col">Deposit</th>
            <th scope="col">Balance</th>
            <th scope="col">Length</th>
            <th scope="col">Waist</th>
            <th scope="col">Update</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>
            {% for c in clothes  %}
          <tr>
            <th scope="row">{{c.id}}</th>
            <td>{{c.style}}</td>
            <td>${{c.price_charge}}</td>
            <td>${{c.deposit}}</td>
            <td>${{c.balance}}</td>
            <td>{{c.length}}</td>
            <td>{{c.waist}}</td>
            <td>
                <a class="btn btn-success" href="{% url 'measurement:clothe-update' c.pk %}">Update</a> 
           </td>
           <td>
            <a class="btn btn-danger" href="{% url 'measurement:clothe-delete' c.pk %}">Delete</a>
        </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
     
    </div>
   
{% endblock content %}

measurement/templates/measurement/home.html
{% extends "measurement/base.html" %}

{% block content %}
<table class="table table-hover mt-2">
    <thead>
      <tr class="table-secondary">
        <th scope="col">CUSTOMER ID</th>
        <th scope="col">FIRST NAME</th>
        <th scope="col">LAST NAME</th>
        <th scope="col">ADDRESS</th>
        <th scope="col">PHONE NUMBER</th>
        <th scope="col">EMAIL</th>
        <th scope="col">DATE JOINED</th>
        <th scope="col">DETAIL</th>
        <th scope="col">UPDATE</th>
        <th scope="col">DELETE</th>
      </tr>
    </thead>
    <tbody>
      {% for customer in customers %}
      <tr class="table-primary">
        <td scope="row">{{customer.pk}}</th>
        <td scope="row">{{customer.first_name}}</th>
        <td>{{customer.last_name}}</td>
        <td>{{customer.adress}}</td>
        <td>{{customer.phone_number}}</td>
        <td>{{customer.email}}</td>
        <td>{{customer.joined_date}}</td>
        <td>
            <a class="btn btn-secondary" href="{% url 'measurement:customer-detail' customer.pk %}">
                Detail
          </a></td>
          <td>
            <a class="btn btn-success" href="{% url 'measurement:customer-update' customer.pk %}">
                update
          </a></td>
          <td>
            <a class="btn btn-danger" href="{% url 'measurement:customer-delete' customer.pk %}">
                Delete
          </a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}